FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    g++ \
    cmake \
    make \
    pkg-config \
    libpoco-dev \
    libpq-dev \
    postgresql-server-dev-14 \
    libssl-dev \
    librdkafka-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN mkdir build && cd build && \
    cmake .. -DBUILD_CONSUMER=ON -DBUILD_API=OFF && \
    make -j$(nproc)

CMD ["./build/consumer"]